server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location = /biometrico {
        return 302 /biometrico/;
    }

    location /biometrico/ {
        try_files $uri $uri/ /biometrico/index.html;
    }

    location = /biometrico/index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        return 404;
    }
}
